using UnityEngine;

/// <summary>
/// The rare self-charging battery, found crated inside dungeon walls (6 per dungeon, hidden in
/// non-ore rock). It looks and handles exactly like an ordinary battery, with three differences:
/// double the tank, it never visits a Battery Station — it refills ITSELF at dawn (that
/// self-charge is its one charge for the day) — and drone logistics never relocate it at base:
/// where it sits is the player's strategic call alone (see the IsPulse gates in
/// BatteryDistribution / BatteryStation). Bag drones still haul freshly-mined crates home from
/// the dungeon — that's acquisition, not placement.
///
/// Two ways home from the dungeon: a bag drone hauls it (their highest-priority find), or the
/// player left-clicks it to take it on as a follower (mechanism-style, if the follower ring has
/// room) — it trails the run and drops loose at base on teleport home.
/// </summary>
public class PulseBattery : Battery
{
    /// <summary>Room check for "is there space in your follower list" — potions + batteries share the ring.</summary>
    public const int MaxFollowers = 6;

    Part followerPart;
    System.Action<bool> teleportAct;
    int homeSortingLayer, homeSortingOrder;   // MechaSuit.RefreshInteractions re-layers part sprites

    public override bool IsPulse => true;

    protected override void Start()
    {
        base.Start();
        maxEnergy *= 2f;   // double an ordinary battery's tank (the prefab is a straight copy)
        RefillToMax();     // pops out of the rock fully charged
        EnsureCoil();
        if (SpawnManager.instance != null) SpawnManager.instance.OnNewDay += SelfCharge;
        if (PortalScript.i != null)
        {
            teleportAct = OnTeleport;
            PortalScript.i.onTeleport += teleportAct;
        }
    }

    /// <summary>Self-heal for the first-generation prefab, which replaced the standard battery
    /// display with a crate animation and shipped without the Coil child. Rebuilds the coil the
    /// way Battery.prefab authors it (local origin, default layer, order 99, the body's
    /// material); a prefab regenerated by the current BatteryKitBuilder arrives wired and skips
    /// this. The stale crate sprite on the body needs no fixing here — the first UpdateVisual
    /// tick (Awake/Start charging set a positive buffer) replaces it with the percent display.</summary>
    void EnsureCoil()
    {
        if (coil != null) return;
        var g = new GameObject("Coil");
        g.transform.SetParent(transform, false);
        coil = g.AddComponent<SpriteRenderer>();
        if (sr != null) coil.sharedMaterial = sr.sharedMaterial;   // sr still holds mats[0] pre-visuals
        coil.sortingOrder = 99;
    }

    /// <summary>The pulse battery's whole point: it charges ITSELF at dawn — and that self-charge
    /// is its once-a-day charge (stations skip pulse batteries entirely).</summary>
    void SelfCharge()
    {
        StampChargedToday();
        RefillToMax();
    }

    // ------------------------------------------------------------------ follower pickup

    /// <summary>In the dungeon a click doesn't cursor-hold the crate — it joins the player's
    /// follower ring (like a mechanism), if there's room. At base it behaves like any battery.</summary>
    public override void OnClick()
    {
        if (following) return;
        if (transform.InDungeon() && held == null)
        {
            TryBecomeFollower();
            return;
        }
        base.OnClick();
    }

    void TryBecomeFollower()
    {
        var m = MechaSuit.m;
        if (m == null) return;
        if (m.followers.Count >= MaxFollowers)
        {
            CM.Message("Pulse Battery: no room in your follower list!");
            return;
        }
        if (claimedBy != null) claimedBy = null;   // outranks a drone's claim; it re-targets next tick
        if (pad != null) pad.UnslotBattery(this);

        if (sr != null)
        {
            homeSortingLayer = sr.sortingLayerID;
            homeSortingOrder = sr.sortingOrder;
        }

        // Minimal mechanism-style follower: a bare Part on the battery itself, ring 10, so
        // MechaSuit.DoFollowers trails it behind the player like a potion.
        followerPart = gameObject.AddComponent<Part>();
        followerPart.taip = Part.PartType.Standalone;
        followerPart.sr = sr;
        followerPart.ring = 10;
        followerPart.engagement = 1f;   // MechaSuit lerps part scale to 0.5 + 0.5*engagement
        m.parts.Add(followerPart);
        m.followers.Add(followerPart);
        transform.SetParent(m.followersParent, true);
        following = true;
        FocusRouter.i?.Deselect(this);
        CM.Message("+Pulse Battery: FOLLOWER");
    }

    /// <summary>Arriving home releases the crate from the ring — it drops loose at the player's
    /// feet for the player to slot somewhere useful (drones won't move it).</summary>
    void OnTeleport(bool nowInDungeon)
    {
        if (!nowInDungeon && following) ReleaseFollower(dropAtPlayer: true);
    }

    void ReleaseFollower(bool dropAtPlayer)
    {
        following = false;
        var p = followerPart;
        followerPart = null;
        if (p != null)
        {
            var m = MechaSuit.m;
            if (m != null)
            {
                m.followers.Remove(p);
                m.parts.Remove(p);
            }
            Destroy(p);
        }
        if (!dropAtPlayer) return;   // whole object is going away — list cleanup was the point
        if (sr != null)
        {
            // undo any re-layering MechaSuit.RefreshInteractions applied while we rode the ring
            sr.sortingLayerID = homeSortingLayer;
            sr.sortingOrder = homeSortingOrder;
        }
        transform.SetParent(GS.FindParent(GS.Parent.loot), true);
        transform.position = GS.CS().position + GS.RandCircle(0.4f, 0.9f);
    }

    protected override void OnDestroy()
    {
        if (following) ReleaseFollower(dropAtPlayer: false);
        if (SpawnManager.instance != null) SpawnManager.instance.OnNewDay -= SelfCharge;
        if (PortalScript.i != null && teleportAct != null) PortalScript.i.onTeleport -= teleportAct;
        base.OnDestroy();
    }
}

/// <summary>The crate face embedded in a dungeon wall (MineField.MakeCrateOverlay): loops the
/// PulseEmberCrate strip so the walled-in battery reads as a live, pulsing thing. AddComponent-only —
/// never referenced from serialized assets.</summary>
public class PulseCrateGlint : MonoBehaviour
{
    public SpriteRenderer sr;
    public Sprite[] frames;
    public float fps = 10f;

    float t;
    int index;

    void Start()
    {
        if (frames != null && frames.Length > 0)
        {
            index = Random.Range(0, frames.Length);   // desync the six crates
            if (sr != null) sr.sprite = frames[index];
        }
    }

    void Update()
    {
        if (sr == null || frames == null || frames.Length == 0) return;
        t += Time.deltaTime * fps;
        if (t < 1f) return;
        t -= 1f;
        index = (index + 1) % frames.Length;
        sr.sprite = frames[index];
    }
}
